/*
Copyright (C) 2013-2015 MetaMorph Software, Inc

Permission is hereby granted, free of charge, to any person obtaining a
copy of this data, including any software or models in source or binary
form, as well as any drawings, specifications, and documentation
(collectively "the Data"), to deal in the Data without restriction,
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Data, and to
permit persons to whom the Data is furnished to do so, subject to the
following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Data.

THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.  

=======================
This version of the META tools is a fork of an original version produced
by Vanderbilt University's Institute for Software Integrated Systems (ISIS).
Their license statement:

Copyright (C) 2011-2014 Vanderbilt University

Developed with the sponsorship of the Defense Advanced Research Projects
Agency (DARPA) and delivered to the U.S. Government with Unlimited Rights
as defined in DFARS 252.227-7013.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this data, including any software or models in source or binary
form, as well as any drawings, specifications, and documentation
(collectively "the Data"), to deal in the Data without restriction,
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Data, and to
permit persons to whom the Data is furnished to do so, subject to the
following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Data.

THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.  
*/

 

// Do not edit
// generated by https://svn.isis.vanderbilt.edu/META/sandbox/DynamicsTeam/test/GenerateDynamicsTeamTest

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Xunit;
using System.IO;
using GME.MGA;

namespace DynamicsTeamTest.Projects
{
    public class RICircuitWithConnectorsFixture : XmeImportFixture
    {
        protected override string xmeFilename
        {
            get { return Path.Combine("RICircuitWithConnectors", "RICircuitWithConnectors.xme"); }
        }
    }

    public partial class RICircuitWithConnectors : IUseFixture<RICircuitWithConnectorsFixture>
    {
        internal string mgaFile { get { return this.fixture.mgaFile; } }
        private RICircuitWithConnectorsFixture fixture { get; set; }

        public void SetFixture(RICircuitWithConnectorsFixture data)
        {
            this.fixture = data;
        }

        //[Fact]
        //[Trait("Model", "RICircuitWithConnectors")]
        //[Trait("ProjectImport/Open", "RICircuitWithConnectors")]
        //public void ProjectXmeImport()
        //{
        //    Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
        //}

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("ProjectImport/Open", "RICircuitWithConnectors")]
        public void ProjectMgaOpen()
        {
            var mgaReference = "MGA=" + mgaFile;

            MgaProject project = new MgaProject();
            project.OpenEx(mgaReference, "CyPhyML", null);
            project.Close(true);
            Assert.True(File.Exists(mgaReference.Substring("MGA=".Length)));
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("CheckerShouldFail", "RICircuitWithConnectors")]
        public void Fail_InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsComponent1()
        {
            string outputDir = "InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsComponent1";
            string testBenchPath = "/@Testing|kind=Testing|relpos=0/@InvalidModelicaConnectorConnections|kind=Testing|relpos=0/@RICircuit_InvalidConnectionsComponent1|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.False(result, "CyPhy2Modelica_v2 should have failed, but did not.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("CheckerShouldFail", "RICircuitWithConnectors")]
        public void Fail_InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsComponent()
        {
            string outputDir = "InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsComponent";
            string testBenchPath = "/@Testing|kind=Testing|relpos=0/@InvalidModelicaConnectorConnections|kind=Testing|relpos=0/@RICircuit_InvalidConnectionsComponent|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.False(result, "CyPhy2Modelica_v2 should have failed, but did not.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("CheckerShouldFail", "RICircuitWithConnectors")]
        public void Fail_InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsTC()
        {
            string outputDir = "InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsTC";
            string testBenchPath = "/@Testing|kind=Testing|relpos=0/@InvalidModelicaConnectorConnections|kind=Testing|relpos=0/@RICircuit_InvalidConnectionsTC|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.False(result, "CyPhy2Modelica_v2 should have failed, but did not.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("CheckerShouldFail", "RICircuitWithConnectors")]
        public void Fail_InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsComponent2()
        {
            string outputDir = "InvalidModelicaConnectorConnections_RICircuit_InvalidConnectionsComponent2";
            string testBenchPath = "/@Testing|kind=Testing|relpos=0/@InvalidModelicaConnectorConnections|kind=Testing|relpos=0/@RICircuit_InvalidConnectionsComponent2|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.False(result, "CyPhy2Modelica_v2 should have failed, but did not.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("CyPhy2Modelica", "RICircuitWithConnectors")]
        public void Testing_RICircuit3Metrics_CA()
        {
            string outputDir = "Testing_RICircuit3Metrics_CA";
            string testBenchPath = "/@Testing|kind=Testing|relpos=0/@RICircuit3Metrics_CA|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.True(result, "CyPhy2Modelica_v2 failed.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("CyPhy2Modelica", "RICircuitWithConnectors")]
        public void Testing_RICircuit_CA()
        {
            string outputDir = "Testing_RICircuit_CA";
            string testBenchPath = "/@Testing|kind=Testing|relpos=0/@RICircuit_CA|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.True(result, "CyPhy2Modelica_v2 failed.");
        }


        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("PET", "RICircuitWithConnectors")]
        public void RI_ResponceSurface3Metrics_CA()
        {
            string outputDir = "RI_ResponceSurface3Metrics_CA";
            string petExperimentPath = "/@Testing|kind=Testing|relpos=0/@PET|kind=ParametricExplorationFolder|relpos=0/@RI_ResponceSurface3Metrics_CA|kind=ParametricExploration|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhyPETRunner.Run(outputDir, mgaFile, petExperimentPath);

            Assert.True(result, "CyPhyPET failed.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("PET", "RICircuitWithConnectors")]
        public void RI_ResponceSurface_CA()
        {
            string outputDir = "RI_ResponceSurface_CA";
            string petExperimentPath = "/@Testing|kind=Testing|relpos=0/@PET|kind=ParametricExplorationFolder|relpos=0/@RI_ResponceSurface_CA|kind=ParametricExploration|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhyPETRunner.Run(outputDir, mgaFile, petExperimentPath);

            Assert.True(result, "CyPhyPET failed.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("PCC", "RICircuitWithConnectors")]
        public void RI_PCC_CA()
        {
            string outputDir = "RI_PCC_CA";
            string petExperimentPath = "/@Testing|kind=Testing|relpos=0/@PCC|kind=ParametricExplorationFolder|relpos=0/@RI_PCC_CA|kind=ParametricExploration|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhyPETRunner.Run(outputDir, mgaFile, petExperimentPath);

            Assert.True(result, "CyPhyPET failed.");
        }

        [Fact]
        [Trait("Model", "RICircuitWithConnectors")]
        [Trait("PCC", "RICircuitWithConnectors")]
        public void RI_PCC3Metrics_CA()
        {
            string outputDir = "RI_PCC3Metrics_CA";
            string petExperimentPath = "/@Testing|kind=Testing|relpos=0/@PCC|kind=ParametricExplorationFolder|relpos=0/@RI_PCC3Metrics_CA|kind=ParametricExploration|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhyPETRunner.Run(outputDir, mgaFile, petExperimentPath);

            Assert.True(result, "CyPhyPET failed.");
        }

    }
}

